project:
  type: website
  output-dir: docs
  resources: 
    - "lgrs/img/"
    - "evnts/img/"

execute:
  freeze: auto

website:
  title: "./jrfep"
  repo-url: https://github.com/jrfep/esp
  repo-branch: mostly-harmless
  repo-actions: [edit, issue]
  navbar:
    title: "J.R. Ferrer-Paris"
    type: inverse
    left:
      - text: "Ciencia y academia"
        icon: bank
        menu:
          - text: "Mis publicaciones"
            href: rzrch/my-publications.qmd
          - rzrch/credit.qmd
          - rzrch/impact.qmd
          - text: "Mis pre-prints"
            href: rzrch/pre-prints.qmd
          - text: "Productos científicos"
            href: rzrch/research-outputs.qmd
          - text: "Eventos"
            href: /mimundo/evnts
      - text: "Biodiversidad"
        icon: binoculars
        menu:
          - text: "Mis ecosistemas favoritos"
            icon: globe
            href: https://jrfep.quarto.pub/ecosystems-of-the-world
          - text: "Mis especies favoritas"
      - text: " Homo faber"
        icon: gear
        menu: 
          - text: "Proyectos reproducibles"
            href: rzrch/my-osfr-projects.qmd
          - text: "Repositorios / código"
            href: rzrch/my-github-repos.qmd
      - text: "Homo ludens"
        icon: balloon
        menu:
          - text: "Mi mundo"
            icon: globe
            href: https://jrfep.github.io/mimundo/
          - text: "Futbol"
            href: j4fun/blog_LaLiga_FinalTemp2019.qmd
          - text: "Todos los nombres"
            href: j4fun/blog_CNE_nombres_Venezuela.Rmd
    right:
      - icon: folder-symlink
        menu:
          - text: "Presentación"
            icon: projector
            href: "https://jrfep.github.io/"
          - text: "switch to English"
            icon: braces-asterisk
            href: "https://jrfep.github.io/eng/"
      - text: "How to..."
        icon: question
        menu:
          - text: "(re-)create this site"
            href: how2/how-to-site.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
lang: es 