---
title: "Ecce Homo"
---

Trabajo en el estudio de ecosistemas y la conservación de la diversidad biológica. Mi investigación [influye en la normativa global](/rzrch/impact.qmd) y nacional sobre conservación de recursos naturales. 

Mis proyectos de investigación aplican métodos informáticos y geomáticos para organizar, acceder, visualizar y analizar una amplia gama de datos ecológicos: registros de distribución de especies, historiales de detección de fototrampeo, interacciones de especies, rasgos de especies o indicadores espaciotemporales de la función del ecosistema. Dichos datos alimentan bases de conocimiento digital que son fundamentales para la toma de decisiones y el desarrollo de políticas públicas y gestión ambiental. 

Los resultados de mi trabajo informan la investigación ecológica, la toma de decisiones en la gestión de riesgos para ecosistemas y especies amenazadas, la restauración y conservación de ecosistemas, y la contabilidad del capital natural. 

La reproducibilidad y transparencia de mi investigación es crítica para infundir confianza entre diferentes grupos de usuarios que apoyan decisiones basadas en evidencia, lo que me impulsa a proporcionar acceso abierto a datos y flujos de trabajo y fomentar la reutilización y validación externa de métodos y resultados.

Actualmente soy [investigador](https://research.unsw.edu.au/people/dr-jose-rafael-ferrer) en la Universidad de New South Wales, Australia. Trabajo en el [Centro de Estudio de Ecosistemas](https://www.unsw.edu.au/research/ecosystem) de la Escuela de Ciencias Biológica, Geológicas y Ambientales. También soy miembro de la Comisión de Manejo de Ecosistemas de la Unión Internacional para la Conservación de la Naturaleza (UICN) y contribuyo activamente con el [Grupo Temático de Lista Roja de Ecosistemas](https://iucnrle.org/team).
